_target_: trl.SFTConfig

learning_rate: 2e-4
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 2
eval_accumulation_steps: 20
num_train_epochs: 10
optim: paged_adamw_32bit
output_dir: output
eval_strategy: steps
eval_steps: 0.05
save_steps: 0.05
warmup_steps: 10
logging_strategy: steps
logging_steps: 1
fp16: False
bf16: False
group_by_length: True
report_to: wandb
run_name: "test_log"
hub_model_id: ueihieu/test_model
push_to_hub: True
metric_for_best_model: eval_loss
save_strategy: steps
greater_is_better: False