learning_rate: 3.0e-4
per_device_train_batch_size: 4
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
eval_accumulation_steps: 20
num_train_epochs: 10
optim: paged_adamw_32bit
output_dir: output
eval_strategy: epoch
# eval_steps: 10
warmup_steps: 10
logging_strategy: steps
logging_steps: 10
fp16: False
bf16: False
group_by_length: True
report_to: wandb
run_name: "test_log"
hub_model_id: ueihieu/test_model
push_to_hub: True
load_best_model_at_end: True
metric_for_best_model: eval_loss
save_strategy: epoch
greater_is_better: False